{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_requests_by_method_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "targets": [
    { "expr": "active_users_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Authentication Attempts/Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "auth/minute" } },
   "targets": [
    {
     "expr": "rate(auth_successful_total[1m])",
     "legendFormat": "__auto"
    },
    { "expr": "rate(auth_failed_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU and Memory Usage Percentages",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage_percent", "legendFormat": "__auto" },
    { "expr": "system_memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizzas Sold/Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pizzas/min" } },
   "targets": [
    { "expr": "rate(pizzas_sold_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Creation Failures",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pizza_creation_failures_total[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_usd_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "http_request_latency_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 14 },
   "targets": [
    {
     "expr": "http_request_latency_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{Total Requests/min}}" }
   ]
  }
 ]
}